parameters:
#    ape_cart.example.class: Ape\CartBundle\Example

services:
#    ape_cart.example:
#        class: %ape_cart.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
